#! /bin/sh
# @(#) $Tau: mx/scripts/docker/entrypoint $

## ------------------------------------------------------------------------- ##
##                          T A U    P R O J E C T                           ##
## ------------------------------------------------------------------------- ##
##                                                                           ##
##  Licensed under the Apache License, Version 2.0 (the "License");          ##
##  you may not use this file except in compliance with the License.         ##
##                                                                           ##
##  You may obtain a copy of the License at:                                 ##
##                                                                           ##
##      http://www.apache.org/licenses/LICENSE-2.0                           ##
##                                                                           ##
##  Unless required by applicable law or agreed to in writing, software      ##
##  distributed under the License is distributed on an "AS-IS" BASIS,        ##
##  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. ##
##  See the License for the specific language governing permissions and      ##
##  limitations under the License.                                           ##
##                                                                           ##
## ------------------------------------------------------------------------- ##
	
case "$1" in
shell)
	exec /bin/sh
	;;
run)
	if test x"$MAILNAME" = x"" ; then
		hostname > /app/config/mailname
	else
		echo  "$MAILNAME" > /app/config/mailname
	fi
	/etc/init.d/inetutils-syslogd start || exit
	/usr/sbin/postfix -c /app/config start || exit
	tail -f /var/log/mail.log
	;;
esac

echo "Usage: $0 shell | run" >&2
exit 255
